name: Ktlint
on:
  pull_request:
    paths:
      - '**/**.kt'
      - '!**/generated/**'
      - '!**/build/**'

jobs:
  ktlint:
    name: Run ktlint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: action-ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          ktlint_version: '0.46.1'
          relative: true
          fail_on_error: true
          reporter: github-pr-check
