name: Ktlint
on: [push]
jobs:
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: musichin/ktlint-check@v2
        with:
          ktlint-version: '0.46.1'

          # ktlint
          relative: true
          experimental: true
          format: true
          reporter: |
            plain,output=ktlint_report.txt
            json,output=ktlint_report.json
          patterns: |
            **/**.kt
            !**/generated/**
            !**/build/**
